name: Release to Production
'on':
    push:
        branches:
            - master
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm run install
            - run: npm run lint
            - run: npm run tsc
            - run: npm run test
            - run: npm run build
